### ISSUE TITLE
ESlint cannot load the plugin

### ISSUE THREAD

**Issue by crystalfp** [kzmat/eslint-plugin-commentout#5]
I'm linting TypeScript code. If I put in my `eslint.yaml` configuration file the two lines as per the README, the plugin is not found. That is:
```
plugins:
    - '@zmat'

rules:
    - '@kzmat/commentout': error
```
ESlint complains that it cannot load the plugin:
```
Oops! Something went wrong! :(

ESLint: 7.32.0

ESLint couldn't find the plugin "@kzmat/eslint-plugin".

(The package "@kzmat/eslint-plugin" was not found when loaded as a Node module from the directory "D:\Projects\AMDIdeaIgniterEnvironment".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install @kzmat/eslint-plugin@latest --save-dev

The plugin "@kzmat/eslint-plugin" was referenced from the config file in "--config".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.
```
Changing the configuration to:
```
plugins:
    - '@zmat/commentout'

rules:
    - '@kzmat/commentout': error
```
For each source file eslint complains: `error: Definition for rule '@kzmat/commentout' was not found (@kzmat/commentout) at ...:1:1:`

If I change the rule to: `- '@kzmat/commentout/commentout' the error becomes: `error: Remove commentout (@kzmat/commentout/commentout) at ...:1:1:`

How should I use this plugin?
Thanks for clarifying!
mario

**Comment by kzmat** [comment]
@crystalfp 
Thank you for reporting the issue.

As you said, 'Usage' in README was incorrect, and I fixed it.
Please refer the latest README 🙇
