### ISSUE TITLE
What is "error: Remove commentout (@kzmat/commentout/commentout) at ..."?

### ISSUE THREAD

**Issue by crystalfp** [kzmat/eslint-plugin-commentout#8]
Added the plugin to eslint as per the corrected README. But now it outputs a not comprehensible error one or more times for each Typescript source file. For example:
```
error: Remove commentout (@kzmat/commentout/commentout) at common\uuid.ts:1:1:
> 1 | import {parse as uuidParse, stringify as uuidStringify} from "uuid";
    | ^
  2 |
  3 | /* eslint-disable no-bitwise, array-plural/array-plural */
  4 | // It is not strictly encoding base64. The sequence in code is different but respects ordering
```
The error is always the same and always reported at the first line of the source. Not very useful, isn't it?

In one of the source I have a big section of code commented out, but this is not reported.

Any incompatibility with Typescript, maybe?
Here is the complete eslint.yaml configuration file.

[eslint.yaml.txt](https://github.com/kzmat/eslint-plugin-commentout/files/7143998/eslint.yaml.txt)

**Comment by kzmat** [comment]
@crystalfp 
Thank you for reporting the issue, and sorry for late response.

I also thought that It was not useful lint report, so I fixed, and published new version.
Please reinstall new version 🙇‍♂️

**Comment by crystalfp** [comment]
Well, a step forward. But now it flags EVERY comment starting with `//`. Some examples:
```
error: Remove inline comment except annotation (@kzmat/commentout/commentout) at prepare\processing-date.ts:19:2:
  17 |
  18 |  /** Path of the file containing the last processing date */
> 19 |  // eslint-disable-next-line unicorn/prefer-module
     |  ^
  20 |  private readonly registerLastProcessingDate = path.join(__dirname, "..", "runtime", "last-import-date.json");
  21 |
  22 |  /**

error: Remove inline comment except annotation (@kzmat/commentout/commentout) at prepare\processing-date.ts:28:2:
  26 |  constructor(private databaseUrl: string) {}
  27 |
> 28 |  // > Get the last process date
     |  ^
  29 |  /**
  30 |   * Get the last process date
  31 |   * @returns The last processed date or zero to signal has never been processed

```
